# Generated by Django 3.0.5 on 2020-04-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_url',
            field=models.URLField(verbose_name='轮播图URL'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link_to',
            field=models.URLField(verbose_name='跳转地址'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='priority',
            field=models.IntegerField(verbose_name='显示顺序'),
        ),
    ]
