# Generated by Django 3.0.5 on 2020-04-04 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_verifycode'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='verifycode',
            table='tb_users_verifycode',
        ),
    ]
