# Generated by Django 3.0.5 on 2020-04-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200421_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofiles',
            old_name='telephone',
            new_name='mobile',
        ),
    ]
