# Generated by Django 3.0.3 on 2020-03-01 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigGoodsTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'big_goods_tag',
            },
        ),
        migrations.CreateModel(
            name='SmallGoodsTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('big_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.BigGoodsTag')),
            ],
            options={
                'db_table': 'small_goods_tag',
            },
        ),
    ]
